### PR TITLE
change the composition of maestro message

### PR DESCRIPTION
**Pull request by byronsym**
- remove the typeName and fromPod

### CODE REVIEW

**Comment by bruceskingle** [comment]
Why do you want to make this change?
Read Receipts and delivery receipts both have the same messageId as the original message, I see no reason to assume that different maestro message types will always have distinct IDs and when you get a xpod message you may get different messages with the same ID from different pods so this change does not seem safe to me.

**Comment by byronsym** [comment]
@bruceskingle 
Read Receipts and delivery receipts both have the same messageId as the original message.  Agree, that's why we need the actor to generate the distinct IDs.

Maestro message, I definitely saw some maestro message with the same messageID. But they are the same message in different pod's of view, by saying that, I assume that should not be two messages with the same messageID in the same pod.  So it makes me think that the tenantID +  messageID should be able to unquie indentify the message.

**Comment by bruceskingle** [comment]
Why take the chance that the same thing which happened with read and delivery receipts wont happen with 2 types of maestro message? What's the advantage of removing the type? And anyway, you have also removed the pod ID

**Comment by byronsym** [comment]
@bruceskingle  Could we take a look at this again?  Thank you

**Comment by bruceskingle** [comment]
You haven't answered my question? Why is this a good idea? Why are you even thinking about this?

**Comment by swchoi727** [comment]
I think we can keep the event type / event name, but do we need the pod id @bruceskingle ?

**Comment by bruceskingle** [comment]
Why are we even having this conversation? What problem are we solving here?

@mattharper what do you think?

**Comment by swchoi727** [comment]
we want to use the LegacyIdFactory to generate object ids and are wondering if it can do without some of the fields, e.g. pod id in a maestro message.

**Comment by bruceskingle** [comment]
LGTM

**Pull request merged**
